# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sut?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # 开启 multipart 上传功能
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

maserhe:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token



## 文件存储所需参数
# 所有通过 REST APIs 上传的文件都将存储在此目录下
file:
  upload-dir: uploads
server:
  port: 8080